[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8001/api/:splat" # Default for local/testing, update in Netlify UI for production
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
