# wrangler.toml
name = "pranitaladdhaprofile"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "public/_worker.js"

[assets]
directory = "dist"

[[kv_namespaces]]
binding = "LEADS_KV"
id = "<your-kv-namespace-id>" # To be created by user in Cloudflare dashboard
